import { Location } from './types';

export const LOCATIONS: Record<string, Location> = {
    dorm_room: {
        id: 'dorm_room',
        name: { en: 'Dorm Room', zh: '宿舍' },
        description: { en: 'Your small but cozy room. It is a bit messy with textbooks scattered around.', zh: '你的小窝，虽然不大但很温馨。有点乱，课本 scattered around。' },
        background: '/assets/backgrounds/dorm_room.png',
        type: 'private',
        interactables: [
            { id: 'bed', label: { en: 'Sleep', zh: '睡觉' }, action: 'examine' },
            { id: 'computer', label: { en: 'Study Online', zh: '在线学习' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave Room', zh: '离开房间' }, action: 'move', target: 'campus_map' },
        ],
    },
    campus_map: {
        id: 'campus_map',
        name: { en: 'Campus Plaza', zh: '校园广场' },
        description: { en: 'The lively heart of Mist City University. Students are everywhere.', zh: '雾城大学的活力中心。学生们到处都是。' },
        background: '/assets/backgrounds/campus_map.png',
        type: 'outdoor',
        timeEffects: {
            morning: 'Students rushing to class, full of energy',
            afternoon: 'Classes in session, quiet pathways',
            evening: 'Students heading to library or dorm',
            night: 'Quiet and peaceful, few people around',
        },
        interactables: [
            { id: 'loc_dorm', label: { en: 'Dorm Building', zh: '宿舍楼' }, action: 'move', target: 'dorm_room' },
            { id: 'loc_library', label: { en: 'University Library', zh: '图书馆' }, action: 'move', target: 'library' },
            { id: 'loc_classroom', label: { en: 'Academic Building', zh: '教学楼' }, action: 'move', target: 'classroom' },
            { id: 'loc_cafeteria', label: { en: 'Student Cafeteria', zh: '学生食堂' }, action: 'move', target: 'cafeteria' },
            { id: 'loc_student_council', label: { en: 'Student Council', zh: '学生会' }, action: 'move', target: 'student_council' },
            { id: 'loc_lab', label: { en: 'Physics Building', zh: '物理楼' }, action: 'move', target: 'lab' },
            { id: 'loc_city', label: { en: 'Enter City', zh: '进入市区' }, action: 'move', target: 'city_map' },
        ],
    },
    library: {
        id: 'library',
        name: { en: 'University Library', zh: '图书馆' },
        description: { en: 'A quiet haven of knowledge. Su Qingqian often studies here.', zh: '知识的安静天堂。苏清浅经常在这里自习。' },
        background: '/assets/backgrounds/library.png',
        type: 'indoor',
        timeEffects: {
            morning: 'Early birds studying, peaceful atmosphere',
            afternoon: 'Students preparing for exams',
            evening: 'Closing soon, quiet atmosphere',
            night: 'Closed for the day',
        },
        accessibility: {
            timeRestrictions: { openHour: 8, closeHour: 22 },
        },
        interactables: [
            { id: 'study_table', label: { en: 'Find a Study Table', zh: '找自习座位' }, action: 'examine' },
            { id: 'bookshelf', label: { en: 'Browse Books', zh: '看书' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave Library', zh: '离开图书馆' }, action: 'move', target: 'campus_map' },
            { id: 'talk_su_qingqian', label: { en: 'Look for Su Qingqian', zh: '找苏清浅' }, action: 'talk', target: 'meet_su_qingqian' },
        ],
    },
    classroom: {
        id: 'classroom',
        name: { en: 'Lecture Hall', zh: '阶梯教室' },
        description: { en: 'A standard university lecture hall. Today\'s class hasn\'t started yet.', zh: '标准的大学阶梯教室。今天还没开始上课。' },
        background: '/assets/backgrounds/classroom.png',
        type: 'indoor',
        timeEffects: {
            morning: 'Students filling in before class',
            afternoon: 'Class in session',
            evening: 'Evening classes about to start',
            night: 'Dark and empty',
        },
        accessibility: {
            timeRestrictions: { openHour: 7, closeHour: 21 },
        },
        interactables: [
            { id: 'desk', label: { en: 'Sit in Front Row', zh: '坐第一排' }, action: 'examine' },
            { id: 'board', label: { en: 'Read Announcements', zh: '看公告' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'campus_map' },
            { id: 'talk_professor', label: { en: 'Attend Class', zh: '上课' }, action: 'talk', target: 'lecture' },
        ],
    },
    cafeteria: {
        id: 'cafeteria',
        name: { en: 'Student Cafeteria', zh: '学生食堂' },
        description: { en: 'Smells of cheap but delicious food. The lunch rush is over.', zh: '飘散着便宜又美味的食物香气。午餐高峰已过。' },
        background: '/assets/backgrounds/cafeteria.png',
        type: 'public',
        timeEffects: {
            morning: 'Breakfast crowd, sleepy students',
            afternoon: 'Lunch rush, crowded and noisy',
            evening: 'Dinner time, moderate crowd',
            night: 'Most stalls closed',
        },
        accessibility: {
            timeRestrictions: { openHour: 6, closeHour: 22 },
        },
        interactables: [
            { id: 'food_counter', label: { en: 'Buy Meal', zh: '买饭' }, action: 'examine' },
            { id: 'table', label: { en: 'Eat and Relax', zh: '吃饭休息' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'campus_map' },
        ],
    },
    student_council: {
        id: 'student_council',
        name: { en: 'Student Council Office', zh: '学生会办公室' },
        description: { en: 'The center of student power. Very organized and professional.', zh: '学生权力的中心。非常整洁有序。' },
        background: '/assets/backgrounds/student_council.png',
        type: 'indoor',
        accessibility: {
            timeRestrictions: { openHour: 8, closeHour: 18 },
        },
        interactables: [
            { id: 'desk', label: { en: 'Check Notices', zh: '查看通知' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'campus_map' },
            { id: 'talk_su_qingqian', label: { en: 'Talk to President', zh: '找会长' }, action: 'talk', target: 'meet_su_qingqian' },
        ],
    },
    lab: {
        id: 'lab',
        name: { en: 'Physics Lab', zh: '物理实验室' },
        description: { en: 'Filled with complex equipment. Ling Ruoyu works here when not in class.', zh: '充满了复杂的设备。凌若羽不在上课时会在这里工作。' },
        background: '/assets/backgrounds/lab.png',
        type: 'indoor',
        accessibility: {
            timeRestrictions: { openHour: 8, closeHour: 22 },
            requiredAffection: {
                ling_ruoyu: 30,
            },
        },
        interactables: [
            { id: 'experiment_table', label: { en: 'Observe Experiment', zh: '观察实验' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'campus_map' },
            { id: 'talk_ling_ruoyu', label: { en: 'Find Prof. Ling', zh: '找凌教授' }, action: 'talk', target: 'meet_ling_ruoyu' },
        ],
    },
    city_map: {
        id: 'city_map',
        name: { en: 'Mist City Center', zh: '雾城市中心' },
        description: { en: 'The bustling city center with shops, cafes, and nightlife.', zh: '繁华的市中心，有商店、咖啡厅和夜生活。' },
        background: '/assets/backgrounds/city_map.png',
        type: 'outdoor',
        timeEffects: {
            morning: 'People heading to work',
            afternoon: 'Shopping and leisure time',
            evening: 'Dinner rush, lively atmosphere',
            night: 'Nightlife in full swing',
        },
        interactables: [
            { id: 'loc_campus', label: { en: 'Return to Campus', zh: '回学校' }, action: 'move', target: 'campus_map' },
            { id: 'loc_mall', label: { en: 'Mist City Mall', zh: '雾城商场' }, action: 'move', target: 'mall' },
            { id: 'loc_cafe', label: { en: 'Chill Cafe', zh: '咖啡厅' }, action: 'move', target: 'cafe' },
            { id: 'loc_bar', label: { en: 'Lucky Star Bar', zh: '幸运星酒吧' }, action: 'move', target: 'bar' },
            { id: 'loc_park', label: { en: 'Central Park', zh: '中央公园' }, action: 'move', target: 'park' },
            { id: 'talk_chen_siyao', label: { en: 'Walk around', zh: '逛街' }, action: 'talk', target: 'meet_chen_siyao' },
        ],
    },
    mall: {
        id: 'mall',
        name: { en: 'Mist City Mall', zh: '雾城商场' },
        description: { en: 'A modern shopping center with international brands and local stores.', zh: '现代化的购物中心，有国际品牌和本地商店。' },
        background: '/assets/backgrounds/mall.png',
        type: 'indoor',
        accessibility: {
            timeRestrictions: { openHour: 10, closeHour: 22 },
        },
        interactables: [
            { id: 'store', label: { en: 'Shop', zh: '购物' }, action: 'examine' },
            { id: 'food_court', label: { en: 'Eat at Food Court', zh: '美食广场吃饭' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'city_map' },
        ],
    },
    cafe: {
        id: 'cafe',
        name: { en: 'Chill Cafe', zh: '咖啡厅' },
        description: { en: 'A cozy cafe with good coffee and Wi-Fi. Popular with students.', zh: '温馨的咖啡厅，咖啡好，有Wi-Fi。受学生欢迎。' },
        background: '/assets/backgrounds/cafe.png',
        type: 'indoor',
        accessibility: {
            timeRestrictions: { openHour: 8, closeHour: 23 },
        },
        interactables: [
            { id: 'table', label: { en: 'Sit Down', zh: '坐下' }, action: 'examine' },
            { id: 'menu', label: { en: 'Order Drink', zh: '点饮料' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'city_map' },
        ],
    },
    bar: {
        id: 'bar',
        name: { en: 'Lucky Star Bar', zh: '幸运星酒吧' },
        description: { en: 'A lively bar with live music. Lu Jiaxin sometimes performs here.', zh: '有现场音乐的活力酒吧。陆嘉欣有时会在这里驻唱。' },
        background: '/assets/backgrounds/bar.png',
        type: 'indoor',
        accessibility: {
            timeRestrictions: { openHour: 18, closeHour: 2 },
            requiredStats: { money: 100 },
        },
        interactables: [
            { id: 'stage', label: { en: 'Watch Performance', zh: '看表演' }, action: 'examine' },
            { id: 'bar', label: { en: 'Order Drink', zh: '点饮料' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'city_map' },
            { id: 'talk_lu_jiaxin', label: { en: 'Look for Lu Jiaxin', zh: '找陆嘉欣' }, action: 'talk', target: 'meet_lu_jiaxin' },
        ],
    },
    park: {
        id: 'park',
        name: { en: 'Central Park', zh: '中央公园' },
        description: { en: 'A peaceful park with trees, benches, and a small lake.', zh: '宁静的公园，有树木、长椅和小湖。' },
        background: '/assets/backgrounds/park.png',
        type: 'outdoor',
        timeEffects: {
            morning: 'Early exercisers and dog walkers',
            afternoon: 'Families having picnics',
            evening: 'Couples walking hand in hand',
            night: 'Quiet and romantic',
        },
        interactables: [
            { id: 'bench', label: { en: 'Sit on Bench', zh: '坐长椅' }, action: 'examine' },
            { id: 'lake', label: { en: 'Feed Ducks', zh: '喂鸭子' }, action: 'examine' },
            { id: 'door', label: { en: 'Leave', zh: '离开' }, action: 'move', target: 'city_map' },
        ],
    },
};
